// ═══════════════════════════════════════════════════════════════════════════
// MODULE 3 — T&C TEMPLATE MANAGER
// 6-slot matrix (RFQ/Contract/Invoice × Local/International). Each cell can
// be activated/deactivated, edited inline (audit-logged), and is pulled into
// document footers via the inheritance engine `getActive(docType, scope)`.
// ═══════════════════════════════════════════════════════════════════════════

import { useMemo, useState } from 'react'
import { FileText, ScrollText, Receipt, CheckCircle2, AlertTriangle, Globe, MapPin, Edit3, Power, X, Save, History } from 'lucide-react'
import useTCTemplateStore from '../../store/tcTemplateStore'
import { TC_DOC_TYPES, TC_SCOPES } from '../../api/mock/tcTemplateData'
import EnterpriseModal, { ModalBtn } from '../../components/ui/EnterpriseModal'
import { useToast } from '../../hooks/useToast'

const C = { background:'var(--card)', borderColor:'var(--border)', boxShadow:'var(--shadow)' }

const DOC_ICONS = {
  rfq:      { icon: FileText,   color: '#2563EB' },
  contract: { icon: ScrollText, color: '#003399' },
  invoice:  { icon: Receipt,    color: '#059669' },
}

const SCOPE_BADGES = {
  local:         { icon: MapPin, label: 'KSA · Local' },
  international: { icon: Globe,  label: 'International' },
}

const CELL_LABELS = {
  'rfq-local':            'Local RFQ Boilerplate',
  'rfq-international':    'International Trade / Incoterms RFQ',
  'contract-local':       'Local Service Level Agreements (SLA)',
  'contract-international':'International Cross-Border Contracts',
  'invoice-local':        'Local VAT / GAZT Compliant Terms',
  'invoice-international':'International Multi-Currency / Duty Disclaimers',
}

function fmtDateTime(iso) {
  if (!iso) return '—'
  return new Date(iso).toLocaleString('en-GB', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' })
}

export default function TCTemplateManager() {
  const { templates, saveBody, setActive } = useTCTemplateStore()
  const { toast } = useToast()

  const [editing, setEditing] = useState(null)        // template object
  const [confirmDeactivate, setConfirmDeactivate] = useState(null)
  const [viewAudit, setViewAudit] = useState(null)

  const stats = useMemo(() => ({
    total:    templates.length,
    active:   templates.filter(t => t.active).length,
    inactive: templates.filter(t => !t.active).length,
  }), [templates])

  // Lookup template at (docType, scope)
  const cell = (docType, scope) => templates.find(t => t.docType === docType && t.scope === scope)

  // ─── Activate / Deactivate ──────────────────────────────────────────────
  const handleToggle = (tpl) => {
    if (tpl.active) {
      // Deactivating an active template — show the warning modal first.
      setConfirmDeactivate(tpl)
    } else {
      setActive(tpl.id, true)
      toast.success('Template activated', `${CELL_LABELS[`${tpl.docType}-${tpl.scope}`]} is now live.`)
    }
  }

  const confirmDeactivateNow = () => {
    if (!confirmDeactivate) return
    setActive(confirmDeactivate.id, false)
    toast.warning('Template deactivated', `${CELL_LABELS[`${confirmDeactivate.docType}-${confirmDeactivate.scope}`]} will no longer be loaded by the document generator.`)
    setConfirmDeactivate(null)
  }

  return (
    <div className="space-y-4">

      {/* Header */}
      <div className="rounded-xl border p-4 flex items-center gap-4" style={C}>
        <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background:'rgba(0,51,153,.1)' }}>
          <ScrollText className="w-5 h-5" style={{ color:'#003399' }} />
        </div>
        <div className="flex-1">
          <h2 className="text-base font-bold" style={{ color:'var(--text)' }}>T&amp;C Template Manager</h2>
          <p className="text-[12.5px]" style={{ color:'var(--text3)' }}>
            Centralized template engine · injects T&amp;C text into the footer of every RFQ, Contract, and Invoice generated by the platform.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="text-center px-3 py-1.5 rounded-lg" style={{ background:'var(--bg2)' }}>
            <div className="text-[9px] font-bold uppercase tracking-widest" style={{ color:'var(--text3)' }}>Total Slots</div>
            <div className="text-base font-mono font-bold" style={{ color:'var(--text)' }}>{stats.total}</div>
          </div>
          <div className="text-center px-3 py-1.5 rounded-lg" style={{ background:'rgba(5,150,105,.08)' }}>
            <div className="text-[9px] font-bold uppercase tracking-widest" style={{ color:'var(--success)' }}>Active</div>
            <div className="text-base font-mono font-bold" style={{ color:'var(--success)' }}>{stats.active}</div>
          </div>
          <div className="text-center px-3 py-1.5 rounded-lg" style={{ background:'rgba(217,119,6,.08)' }}>
            <div className="text-[9px] font-bold uppercase tracking-widest" style={{ color:'#D97706' }}>Inactive</div>
            <div className="text-base font-mono font-bold" style={{ color:'#D97706' }}>{stats.inactive}</div>
          </div>
        </div>
      </div>

      {/* The 6-slot matrix */}
      <div className="rounded-xl border overflow-hidden" style={C}>
        <table className="w-full" style={{ borderCollapse:'collapse' }}>
          <thead>
            <tr style={{ background:'var(--bg2)' }}>
              <th className="text-left px-4 py-3 text-[10px] font-bold uppercase tracking-widest" style={{ color:'var(--text3)', width:'25%' }}>
                Document Type
              </th>
              {TC_SCOPES.map(s => {
                const Badge = SCOPE_BADGES[s.id].icon
                return (
                  <th key={s.id} className="text-left px-4 py-3 text-[10px] font-bold uppercase tracking-widest" style={{ color:'var(--text3)' }}>
                    <div className="flex items-center gap-1.5">
                      <Badge className="w-3.5 h-3.5" style={{ color:'var(--text2)' }} />
                      {SCOPE_BADGES[s.id].label}
                    </div>
                  </th>
                )
              })}
            </tr>
          </thead>
          <tbody>
            {TC_DOC_TYPES.map(d => {
              const Icon = DOC_ICONS[d.id].icon
              const color = DOC_ICONS[d.id].color
              return (
                <tr key={d.id} style={{ borderTop:'1px solid var(--border)' }}>
                  <td className="px-4 py-4" style={{ verticalAlign:'top' }}>
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background:`${color}15` }}>
                        <Icon className="w-4 h-4" style={{ color }} />
                      </div>
                      <div>
                        <div className="text-sm font-bold" style={{ color:'var(--text)' }}>{d.label}</div>
                        <div className="text-[10px]" style={{ color:'var(--text3)' }}>2 templates · 1 per scope</div>
                      </div>
                    </div>
                  </td>
                  {TC_SCOPES.map(s => {
                    const tpl = cell(d.id, s.id)
                    if (!tpl) return <td key={s.id} className="px-4 py-4"></td>
                    return (
                      <td key={s.id} className="px-4 py-4" style={{ verticalAlign:'top', borderLeft:'1px solid var(--border)' }}>
                        <TemplateCell tpl={tpl} color={color}
                          onEdit={() => setEditing(tpl)}
                          onToggle={() => handleToggle(tpl)}
                          onAudit={() => setViewAudit(tpl)} />
                      </td>
                    )
                  })}
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Inheritance engine note */}
      <div className="rounded-xl p-3 flex items-start gap-2.5 border" style={{ background:'rgba(37,99,235,.06)', borderColor:'rgba(37,99,235,.3)' }}>
        <CheckCircle2 className="w-4 h-4 flex-shrink-0 mt-0.5" style={{ color:'var(--primary)' }} />
        <div className="text-[12.5px]" style={{ color:'var(--text2)' }}>
          <strong style={{ color:'var(--primary)' }}>Inheritance Engine</strong>
          {' '}— Whenever an RFQ, Contract, or Invoice is generated by the platform, the corresponding <strong>Active</strong> template above is automatically pulled and embedded into the document footer / appendix.
          Inactive templates are skipped and the user is asked to pick a substitute before proceeding.
        </div>
      </div>

      {/* ─── Edit modal ─────────────────────────────────────────────────── */}
      {editing && (
        <EditorModal tpl={editing} onClose={() => setEditing(null)}
          onSave={(body) => { saveBody(editing.id, body); toast.success('Template saved', `${CELL_LABELS[`${editing.docType}-${editing.scope}`]} · v${editing.version + 1}`); setEditing(null) }} />
      )}

      {/* ─── Deactivate confirmation modal ──────────────────────────────── */}
      <EnterpriseModal open={!!confirmDeactivate} onClose={() => setConfirmDeactivate(null)}
        title="Deactivate Template?"
        subtitle={confirmDeactivate ? CELL_LABELS[`${confirmDeactivate.docType}-${confirmDeactivate.scope}`] : ''}
        icon={<AlertTriangle className="w-4 h-4" style={{ color:'var(--warning)' }} />} size="md"
        footer={<><ModalBtn variant="secondary" onClick={() => setConfirmDeactivate(null)}>Cancel</ModalBtn><ModalBtn variant="danger" onClick={confirmDeactivateNow}>Deactivate Anyway</ModalBtn></>}>
        <div className="rounded-lg p-3 mb-2 text-[12.5px]" style={{ background:'rgba(217,119,6,.08)', border:'1px solid rgba(217,119,6,.3)', color:'#D97706' }}>
          <strong>Warning:</strong> This template is tied to active workflows. Deactivating will force users to manually select an alternative template before generating new documents in this category.
        </div>
        <p className="text-[12.5px]" style={{ color:'var(--text2)' }}>
          Existing documents already generated using this template are not affected. Audit history is preserved.
        </p>
      </EnterpriseModal>

      {/* ─── Audit modal ────────────────────────────────────────────────── */}
      <EnterpriseModal open={!!viewAudit} onClose={() => setViewAudit(null)}
        title="Template Audit Trail"
        subtitle={viewAudit ? `${CELL_LABELS[`${viewAudit.docType}-${viewAudit.scope}`]} · v${viewAudit.version}` : ''}
        icon={<History className="w-4 h-4" style={{ color:'var(--primary)' }} />} size="lg"
        footer={<ModalBtn onClick={() => setViewAudit(null)}>Close</ModalBtn>}>
        {viewAudit && (
          <div className="space-y-1.5">
            {[...viewAudit.audit].reverse().map(a => (
              <div key={a.id} className="rounded-lg p-2.5 flex items-start gap-2 text-[12.5px]" style={{ background:'var(--bg2)', border:'1px solid var(--border)' }}>
                <div className="w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0" style={{ background:'var(--card)', color:'var(--primary)' }}>•</div>
                <div className="flex-1">
                  <div style={{ color:'var(--text)' }}><strong>{a.actor}</strong> · {a.action}</div>
                  <div className="text-[10px] font-mono" style={{ color:'var(--text3)' }}>{fmtDateTime(a.at)}</div>
                </div>
              </div>
            ))}
          </div>
        )}
      </EnterpriseModal>
    </div>
  )
}

// ─── One cell ───────────────────────────────────────────────────────────────
function TemplateCell({ tpl, color, onEdit, onToggle, onAudit }) {
  const preview = (tpl.body ?? '').split('\n').filter(l => l.trim()).slice(0, 3).join(' · ').slice(0, 140)
  return (
    <div className="rounded-lg border-2 p-3 transition-all"
      style={{ borderColor: tpl.active ? color : 'var(--border)', background: tpl.active ? `${color}05` : 'var(--bg2)' }}>
      <div className="flex items-center gap-1.5 mb-1.5">
        <span className="text-[12.5px] font-bold flex-1" style={{ color: tpl.active ? color : 'var(--text2)' }}>
          {CELL_LABELS[`${tpl.docType}-${tpl.scope}`]}
        </span>
        <span className="text-[9px] font-bold px-1.5 py-0.5 rounded-full uppercase tracking-widest" style={{
          background: tpl.active ? 'rgba(5,150,105,.12)' : 'rgba(217,119,6,.12)',
          color: tpl.active ? 'var(--success)' : '#D97706',
        }}>
          {tpl.active ? '● Active' : '○ Inactive'}
        </span>
      </div>
      <div className="text-[11px] font-mono mb-2" style={{ color:'var(--text3)' }}>v{tpl.version} · updated {fmtDateTime(tpl.updatedAt)}</div>
      <div className="text-[11px] line-clamp-3 mb-2" style={{ color:'var(--text2)' }}>{preview}…</div>
      <div className="flex items-center gap-1.5">
        <button onClick={onEdit}
          className="flex-1 px-2 py-1 text-[10px] font-bold rounded border flex items-center justify-center gap-1 transition-colors hover:bg-slate-50"
          style={{ background:'var(--card)', borderColor:'var(--border)', color:'var(--text2)' }}>
          <Edit3 className="w-2.5 h-2.5" /> Edit
        </button>
        <button onClick={onToggle}
          className="flex-1 px-2 py-1 text-[10px] font-bold rounded border flex items-center justify-center gap-1 transition-colors"
          style={{
            background: tpl.active ? 'var(--card)' : color,
            borderColor: tpl.active ? 'var(--border)' : color,
            color: tpl.active ? 'var(--warning)' : '#fff',
          }}>
          <Power className="w-2.5 h-2.5" /> {tpl.active ? 'Deactivate' : 'Activate'}
        </button>
        <button onClick={onAudit}
          className="px-2 py-1 text-[10px] font-bold rounded border flex items-center justify-center"
          style={{ background:'var(--card)', borderColor:'var(--border)', color:'var(--text3)' }}
          title="View audit history">
          <History className="w-2.5 h-2.5" />
        </button>
      </div>
    </div>
  )
}

// ─── Editor modal ───────────────────────────────────────────────────────────
function EditorModal({ tpl, onClose, onSave }) {
  const [body, setBody] = useState(tpl.body ?? '')
  const dirty = body !== (tpl.body ?? '')
  const lines = body.split('\n').length

  return (
    <EnterpriseModal open onClose={onClose}
      title="Edit Template"
      subtitle={`${CELL_LABELS[`${tpl.docType}-${tpl.scope}`]} · v${tpl.version}`}
      icon={<Edit3 className="w-4 h-4" style={{ color:'var(--primary)' }} />} size="xl"
      footer={<>
        <ModalBtn variant="secondary" onClick={onClose}>Cancel</ModalBtn>
        <ModalBtn onClick={() => onSave(body)} disabled={!dirty}>
          <Save className="w-3.5 h-3.5" /> Save · creates v{tpl.version + 1}
        </ModalBtn>
      </>}>
      <div className="space-y-2">
        <div className="text-[10px] font-mono" style={{ color:'var(--text3)' }}>
          {body.length} characters · {lines} line{lines === 1 ? '' : 's'} {dirty && (<span style={{ color:'var(--warning)' }}>· unsaved changes</span>)}
        </div>
        <textarea value={body} onChange={e => setBody(e.target.value)} rows={22}
          className="w-full rounded-lg p-3 text-[11.5px] border focus:outline-none font-mono resize-none"
          style={{ background:'var(--bg2)', borderColor:'var(--border)', color:'var(--text)', lineHeight: 1.6 }} />
      </div>
    </EnterpriseModal>
  )
}
